package me.pm7.particleLibExamples.listeners;

import me.pm7.particleLibExamples.ParticleLibExamples;
import me.pm7.particlelib.ParticleManager;
import me.pm7.particlelib.data.Direction;
import me.pm7.particlelib.emitter.ParticleEmitterBurst;
import me.pm7.particlelib.data.gradient.RangedGradientVector;
import me.pm7.particlelib.data.keyframe.EasingMode;
import me.pm7.particlelib.data.keyframe.RangedKeyframe;
import me.pm7.particlelib.data.keyframe.ValueRange;
import me.pm7.particlelib.physics.GravityDirection;
import me.pm7.particlelib.particlebuilder.ParticleBuilderBlock;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.util.Vector;

public class BlockBreak implements Listener {

    /*
    Creates a breaking particle whenever a block is broken
     */

    // The particle data for blocks being broken
    private final ParticleBuilderBlock particleData = new ParticleBuilderBlock()
            .particleLifeTicks(new ValueRange<>(26, 34))
            .gravity(new GravityDirection()
                    .initialSpeed(3.0)
                    .strengthOverLifetime(16)
                    .bouncinessOverLifetime(0.5)
            )
            .spawnOffset(new ValueRange<>(
                    new Vector(-0.4, -0.4, -0.4),
                    new Vector(0.4, 0.4, 0.4)
            ))
            .initialMovementDirection(new ValueRange<>(
                    new Direction(0, 30),
                    new Direction(360, 150)
            ))
            .initialRotation(new ValueRange<>(
                    new Vector(0, 0, 0),
                    new Vector(360, 360, 360)
            ))
            .scaleOverLifetime(new RangedGradientVector(
                    EasingMode.LINEAR,
                    new RangedKeyframe<>(new Vector(0.125, 0.125, 0.125), new Vector(0.106, 0.106, 0.106), 0.8),
                    new RangedKeyframe<>(new Vector(0, 0, 0), 1.0)
            ))
            .rotationOverVelocity(new ValueRange<>(120.0, 140.0))
    ;

    @EventHandler
    public void onBlockBreak(BlockBreakEvent e) {
        /*
        Set the particle's block data to block data generated by the material of whatever was just broken. I think this
        errors whenever you break something like a wall hanging torch or other specific block states but I don't really
        care to fix that
         */
        particleData.blockData(e.getBlock().getBlockData());
        Location loc = e.getBlock().getLocation().add(0.5, 0.5, 0.5);

        new ParticleEmitterBurst(25, particleData, loc).start();
    }

}
